package cli

// zshScript is the completion script for zsh.
//
// It is shorter than the bash one for a real reason rather than by omission.
// zsh's _git resolves "git ticket" itself and calls _git-ticket with the git
// word and its options already consumed, so $words[1] is the command word and
// $words[2] onward are this tool's arguments in both invocations. bash hands
// its handler the raw words and leaves the normalizing to the script.
//
// The function name carries a hyphen and bash's carries underscores. That is
// not a style choice: zsh calls _git-$words[1] and bash computes
// _git_${command//-/_}, so the two cannot share a name.
const zshScript = `#compdef git-ticket
#description repository-native work ledger

# zsh completion for git-ticket.
#
# Generated by: git ticket completion zsh
# Do not edit this file. Regenerate it, so it follows the binary.
#
# Install as the file name "_git-ticket" in a directory on your $fpath, added
# before compinit runs. The name matters twice: zsh's _git scans $fpath for
# _git-* files to decide what to offer after "git <TAB>", and it calls the
# function _git-ticket to complete "git ticket <TAB>".
#
# Everything offered comes from "git-ticket completion --dump", so a command or
# a flag added to the binary completes with no edit here.

__git_ticket_dump=""

__git_ticket_field() {
    if [[ -z $__git_ticket_dump ]]; then
        __git_ticket_dump=$(git-ticket completion --dump 2>/dev/null)
    fi
    print -r -- $__git_ticket_dump | awk -F'\t' "$@"
}

_git-ticket() {
    local sub prev name usage token lower values
    local -a candidates
    local -i i argpos cmdidx

    # $words[1] is the command word in both invocations: git-ticket when
    # completing the binary directly, and ticket when zsh's _git dispatches
    # here. Either way $words[2] onward are this tool's own arguments.
    sub=""
    cmdidx=0
    for (( i = 2; i < CURRENT; i++ )); do
        case ${words[i]} in
            --*=*) ;;
            -*)
                if [[ $(__git_ticket_field -v f="${words[i]#--}" \
                    '$1=="flag" && $3==f {print $4; exit}') == 1 ]]; then
                    (( i++ ))
                fi
                ;;
            *)
                sub=${words[i]}
                cmdidx=$i
                break
                ;;
        esac
    done

    if [[ -z $sub ]]; then
        candidates=(${(f)"$(__git_ticket_field '$1=="cmd"{print $2 ":" $5}')"})
        _describe -t commands 'git-ticket command' candidates
        return
    fi

    # A value for the flag just typed. Offer the enum when the flag names one,
    # and otherwise nothing rather than guessing at a path.
    prev=${words[CURRENT-1]}
    if [[ $prev == --* ]]; then
        name=${prev#--}
        if [[ $(__git_ticket_field -v c="$sub" -v f="$name" \
            '$1=="flag" && $3==f && (c=="" || $2==c) {print $4; exit}') == 1 ]]; then
            values=$(__git_ticket_field -v n="$name" '$1=="enum" && $2==n {print $3}')
            if [[ -n $values ]]; then
                compadd -- ${=values}
            fi
            return
        fi
    fi

    if [[ ${words[CURRENT]} == -* ]]; then
        candidates=(${(f)"$(__git_ticket_field -v c="$sub" '$1=="flag" && $2==c {print "--" $3}')"})
        compadd -- $candidates
        return
    fi

    # Which positional this is, counting bare words after the command.
    argpos=0
    for (( i = cmdidx + 1; i < CURRENT; i++ )); do
        case ${words[i]} in
            --*=*) ;;
            -*)
                if [[ $(__git_ticket_field -v c="$sub" -v f="${words[i]#--}" \
                    '$1=="flag" && $2==c && $3==f {print $4; exit}') == 1 ]]; then
                    (( i++ ))
                fi
                ;;
            *) (( argpos++ )) ;;
        esac
    done

    # The usage line says what goes here. ID means a ticket, and an upper-case
    # token naming an enum means that enum, so neither is written down twice.
    usage=$(__git_ticket_field -v c="$sub" '$1=="cmd" && $2==c {print $4}')
    token=${${(z)usage}[argpos+1]}

    if [[ $token == ID ]]; then
        # zsh shows a description beside each candidate, so the title comes
        # too. A bare ULID is close to unpickable.
        candidates=(${(f)"$(git-ticket completion --ids ${words[CURRENT]} 2>/dev/null | sed 's/\t/:/')"})
        _describe -t tickets 'ticket' candidates
        return
    fi

    lower=${token:l}
    if [[ -n $lower ]]; then
        values=$(__git_ticket_field -v n="$lower" '$1=="enum" && $2==n {print $3}')
        if [[ -n $values ]]; then
            compadd -- ${=values}
        fi
    fi
}

# Autoloaded from $fpath, the file body is the function body on the first call,
# so it has to invoke the function it just defined. Sourced from .zshrc, there
# is no binding yet and one has to be made.
if [[ $funcstack[1] == "_git-ticket" ]]; then
    _git-ticket "$@"
else
    compdef _git-ticket git-ticket
fi
`
