package cli

// bashScript is the completion script for bash.
//
// It is one file serving both invocation forms, which is what git's own
// completion makes possible. Typing "git ticket <TAB>" reaches
// __git_complete_command, which computes the handler name _git_${command//-/_}
// and, not finding it, asks bash-completion's loader for a file named
// git-ticket. Typing "git-ticket <TAB>" reaches the same file through the
// complete registration at the bottom. So the file has to be installed under
// the binary's name for either path to find it.
//
// Nothing in it restates what the binary accepts. Every command, flag and enum
// value comes from "git-ticket completion --dump", so adding a command to the
// dispatch table makes it complete with no edit here.
const bashScript = `# bash completion for git-ticket.
#
# Generated by: git ticket completion bash
# Do not edit this file. Regenerate it, so it follows the binary.
#
# Install as the file name "git-ticket" in a bash-completion directory, such as
#   ${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions/git-ticket
# The name matters: it is what git's completion asks the loader for when you
# type "git ticket <TAB>".

__git_ticket_dump=""

__git_ticket_load() {
    if [ -z "$__git_ticket_dump" ]; then
        __git_ticket_dump=$(git-ticket completion --dump 2>/dev/null)
    fi
}

__git_ticket_field() {
    __git_ticket_load
    printf '%s\n' "$__git_ticket_dump" | awk -F'\t' "$@"
}

__git_ticket_commands() {
    __git_ticket_field '$1=="cmd"{print $2}'
}

__git_ticket_usage() {
    __git_ticket_field -v c="$1" '$1=="cmd" && $2==c {print $4}'
}

__git_ticket_flags() {
    __git_ticket_field -v c="$1" '$1=="flag" && $2==c {print "--" $3}'
}

# Reports 1 when a flag takes a value. An empty command matches the flag under
# any command, which is how the global flags are resolved before the command
# word has been found.
__git_ticket_flag_takes_value() {
    __git_ticket_field -v c="$1" -v f="$2" \
        '$1=="flag" && $3==f && (c=="" || $2==c) {print $4; exit}'
}

__git_ticket_enum() {
    __git_ticket_field -v n="$1" '$1=="enum" && $2==n {print $3}'
}

__git_ticket_ids() {
    git-ticket completion --ids "$1" 2>/dev/null | cut -f1
}

# git registers its completion wrapper with -o nospace, so a finished word gets
# no trailing space unless we add one. The registration at the bottom uses
# -o nospace as well, so both invocation forms behave the same.
__git_ticket_reply() {
    COMPREPLY=($(compgen -W "$1" -- "$__git_ticket_cur"))
    if [ ${#COMPREPLY[@]} -eq 1 ]; then
        COMPREPLY[0]="${COMPREPLY[0]} "
    fi
}

__git_ticket_dispatch() {
    local words cword cur
    words=("${__git_ticket_words[@]}")
    cword=$__git_ticket_cword
    cur=$__git_ticket_cur

    # The command word is the first bare word after the binary. Global flags
    # may precede it, because parseFlags consumes one positional per pass and
    # so accepts them anywhere.
    local cmd="" cmdidx=0 i=1 w
    while [ $i -lt $cword ]; do
        w=${words[i]}
        case "$w" in
            --*=*) ;;
            -*)
                if [ "$(__git_ticket_flag_takes_value "" "${w#--}")" = "1" ]; then
                    i=$((i + 1))
                fi
                ;;
            *)
                cmd=$w
                cmdidx=$i
                break
                ;;
        esac
        i=$((i + 1))
    done

    if [ -z "$cmd" ]; then
        __git_ticket_reply "$(__git_ticket_commands)"
        return
    fi

    # A value for the flag just typed. Offer the enum when the flag's name is
    # one, and otherwise offer nothing rather than guessing at a path.
    local prev name
    prev=${words[cword - 1]}
    case "$prev" in
        --*)
            name=${prev#--}
            if [ "$(__git_ticket_flag_takes_value "$cmd" "$name")" = "1" ]; then
                local values
                values=$(__git_ticket_enum "$name")
                if [ -n "$values" ]; then
                    __git_ticket_reply "$values"
                else
                    COMPREPLY=()
                fi
                return
            fi
            ;;
    esac

    case "$cur" in
        -*)
            __git_ticket_reply "$(__git_ticket_flags "$cmd")"
            return
            ;;
    esac

    # Which positional this is, counting bare words after the command.
    local argpos=0 j=$((cmdidx + 1))
    while [ $j -lt $cword ]; do
        w=${words[j]}
        case "$w" in
            --*=*) ;;
            -*)
                if [ "$(__git_ticket_flag_takes_value "$cmd" "${w#--}")" = "1" ]; then
                    j=$((j + 1))
                fi
                ;;
            *) argpos=$((argpos + 1)) ;;
        esac
        j=$((j + 1))
    done

    # The usage line says what goes here. ID means a ticket, and an upper-case
    # token naming an enum means that enum, so neither is written down twice.
    local usage token lower values
    usage=$(__git_ticket_usage "$cmd")
    token=$(printf '%s\n' "$usage" | awk -v n=$((argpos + 1)) '{print $n}')
    case "$token" in
        ID)
            __git_ticket_reply "$(__git_ticket_ids "$cur")"
            return
            ;;
    esac
    lower=$(printf '%s' "$token" | tr 'A-Z' 'a-z')
    if [ -n "$lower" ]; then
        values=$(__git_ticket_enum "$lower")
        if [ -n "$values" ]; then
            __git_ticket_reply "$values"
            return
        fi
    fi
    COMPREPLY=()
}

# Entry point for "git-ticket <TAB>".
__git_ticket_main() {
    __git_ticket_words=("${COMP_WORDS[@]}")
    __git_ticket_cword=$COMP_CWORD
    __git_ticket_cur=${COMP_WORDS[COMP_CWORD]}
    __git_ticket_dispatch
}

# Entry point for "git ticket <TAB>". git's completion calls this with no
# arguments, having already set cur, words and cword through __git_func_wrap.
# __git_cmd_idx is the index of the subcommand word, so "git -C dir ticket"
# lands in the right place.
_git_ticket() {
    local i=${__git_cmd_idx:-1}
    __git_ticket_words=("git-ticket" "${words[@]:i+1}")
    __git_ticket_cword=$((cword - i))
    __git_ticket_cur=$cur
    __git_ticket_dispatch
}

complete -o bashdefault -o default -o nospace -F __git_ticket_main git-ticket
`
