package ticket

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// epicsFile is the generated type view, per plan section 4. Directories key on
// status and the plan refuses to key them on type, so `list --type epic` has no
// equivalent in a file browser. This file is that equivalent.
const epicsFile = "epics.md"

// epicsPreamble says who writes this file and what happens to a hand edit. It
// is prose for a person, because the tool never reads this file back.
const epicsPreamble = `# Epics

Generated by ` + "`git ticket check --fix`" + `. Editing it by hand is safe but
pointless: ` + "`git ticket check`" + ` reports it stale until it agrees with the
tickets, and the next fix pass overwrites it.
`

// renderEpicsIndex builds the index from the tickets, byte for byte.
//
// The output has to be stable or every check would report a file it just wrote
// as stale, so the rows are sorted by ID and nothing here reads a clock.
//
// A row holds the ID, the title, the status, and a link, per section 4. Nothing
// derived from other tickets appears, because a child count would stale this
// file whenever any ticket changed status and send CI red on a commit that
// touched no epic.
func renderEpicsIndex(all []*Ticket) []byte {
	epics := make([]*Ticket, 0)
	for _, t := range all {
		// An exclusion, not a list of the statuses that qualify. A status added
		// to 6.1 later appears here with no edit, where an inclusion list would
		// drop it silently.
		if t.Type != "epic" || TerminalStatus(t.Status) {
			continue
		}
		epics = append(epics, t)
	}
	sort.Slice(epics, func(i, j int) bool { return epics[i].ID < epics[j].ID })

	var b bytes.Buffer
	b.WriteString(epicsPreamble)
	b.WriteString("\n")
	if len(epics) == 0 {
		// Said outright rather than left as an empty table, because an empty
		// table reads like a rendering fault.
		b.WriteString("No epics.\n")
		return b.Bytes()
	}
	b.WriteString("| Epic | Title | Status |\n|---|---|---|\n")
	for _, t := range epics {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s |\n",
			t.ID, statusDir(t.Status)+"/"+t.ID+".md", escapeCell(t.Title), t.Status)
	}
	return b.Bytes()
}

// epicsIndexStale reports whether epics.md disagrees with the tickets, and the
// bytes it should hold.
//
// A missing file is stale rather than nothing to say. A store that never
// generated one and a store whose index somebody deleted are the same condition
// with the same repair, and treating absence as acceptable would mean the
// warning never fires for the store that needs it most.
//
// init writes this file for the same reason, so a fresh store is not born
// reporting a warning it did nothing to earn.
func (s *Store) epicsIndexStale(parsed []file) (want []byte, stale bool) {
	all := make([]*Ticket, 0, len(parsed))
	for _, f := range parsed {
		all = append(all, f.Ticket)
	}
	want = renderEpicsIndex(all)
	got, err := os.ReadFile(filepath.Join(s.path, epicsFile))
	return want, err != nil || !bytes.Equal(got, want)
}

// escapeCell keeps a title from breaking the row it sits in. A pipe would end
// the cell early and a newline would end the row, and a title is free text that
// nothing else validates.
func escapeCell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.ReplaceAll(s, "\n", " ")
}
